### ISSUE TITLE
contact Prof. Ernecker for details about the Rocket

### ISSUE THREAD

**Issue by Dumfarth-Felix** [htl-leonding-project/rocketman#3]

**Comment by Dumfarth-Felix** [comment]
Prof. Ernecker wrote back he is sick and that he will contact us in the future

**Comment by htl-leonding** [comment]
where can you find this details?

**Comment by FeichtingerSarah** [comment]
> where can you find this details?

**Besprechung am 27.11.2020:**

Datenübertragung:
	2 Frequenzbereiche
	WLAN mit Videoübertragung 
	Messdaten Übertragung bzw. Form selbst ausdenken
	XP Antennen, 3 Antennen vorhanden

Daten die von der Rakete gesendet werden:
	Primärmission - Luftdruck & Temperatur
	Sekundermission - beliebige Daten z.B. Luftqualität, Ozon
	
Zünder:
	Brückenzünder
	Wiederstand messen
	In Software einstellen wieviele Zünder, so dass der soll Wiederstand berechnet 	werden kann
	
Persistente Daten:
	Config Files für (Vor)Einstellungen
	Video ja/nein
	
Versorgung:
	Mit 230v dauerladen von Akkus?
	Berechnen wieviel Leisutng benötigt wird (Raspi, Monitore, Zündimpuls - dieser kann auch direkt von der Batterie kommen, nicht über USV-Elektronik,..)
