### ISSUE TITLE
Meeting with Prof. Bernecker

### ISSUE THREAD

**Issue by Dumfarth-Felix** [htl-leonding-project/rocketman#62]
Starts der Geräte sind zu speichern
Die Außenstellen auch mit ID und Name 
Flüge sollen auch Kommentare haben können

Auf Weboberfläche: 
zündplan,zündpunkte – nein
akkuspannung und wiederstand(kurzschluss warnung), Außenstellen – ja

Wenn Flug beendet vlt. Signal aussenden

Touchscreen:
Akkustand!

Es muss kein Web Archiv geben außer es ist einfacher

Excel Liste aus Daten

Unter umständen ein paar Rechnungen => z.b.: Aus Luftdruck die Fallgeschwindigkeit

Powerbank nicht herumbasteln, Einschalt Knopf einfach erreichbar machen

**Comment by FeichtingerSarah** [comment]
Daten sollen von Koffer direkt auf Stick geladen werden können
